### ISSUE TITLE
buildcpp does not report errors reported by cam configure

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#1045]
### What happened?

I ran test SMS_Ln9_D.ne30pg3_ne30pg3_mg17.FADIAB.derecho_intel.cam-outfrq9s
with `./xmlchange --append CAM_CONFIG_OPTS="-chem trop_mam4"`
and I get an error:
```
Traceback (most recent call last):
  File "/glade/derecho/scratch/jedwards/SMS_Ln9_D.ne30pg3_ne30pg3_mg17.FADIAB.derecho_intel.cam-outfrq9s.20240528_110421_r2qhrk/./case.build", line 267, in <module>
    _main_func(__doc__)
  File "/glade/derecho/scratch/jedwards/SMS_Ln9_D.ne30pg3_ne30pg3_mg17.FADIAB.derecho_intel.cam-outfrq9s.20240528_110421_r2qhrk/./case.build", line 241, in _main_func
    success = test.build(
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/SystemTests/system_tests_common.py", line 185, in build
    self._resetup_case(phase_name)
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/SystemTests/system_tests_common.py", line 156, in _resetup_case
    self._case.case_setup(reset=True, test_mode=True)
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/case/case_setup.py", line 505, in case_setup
    run_and_log_case_status(
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/utils.py", line 2480, in run_and_log_case_status
    rv = func()
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/case/case_setup.py", line 473, in <lambda>
    functor = lambda: _case_setup_impl(
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/case/case_setup.py", line 451, in _case_setup_impl
    case.create_namelists()
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/case/preview_namelists.py", line 90, in create_namelists
    import_and_run_sub_or_cmd(
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/utils.py", line 666, in import_and_run_sub_or_cmd
    raise e1 from None
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/utils.py", line 662, in import_and_run_sub_or_cmd
    run_sub_or_cmd(
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/cime/CIME/utils.py", line 707, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/glade/work/jedwards/sandboxes/cesm2_3_beta17/components/cam//cime_config/buildnml", line 81, in buildnml
    raise RuntimeError("CAM's 'buildcpp' script failed to run properly.")
RuntimeError: CAM's 'buildcpp' script failed to run properly.

```
Nowhere in this is the information needed to diagnose and solve the problem.

### What are the steps to reproduce the bug?

see above

### What CAM tag were you using?

cam6_3_160

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/derecho/scratch/jedwards/SMS_Ln9_D.ne30pg3_ne30pg3_mg17.FADIAB.derecho_intel.cam-outfrq9s.20240528_110421_r2qhrk

### Will you be addressing this bug yourself?

Yes

**Comment by brian-eaton** [comment]
resolved by PR#1072 (cam6_4_015)
